# Generated by Django 3.1.7 on 2021-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Картинка статьи'),
        ),
    ]
